<?php

namespace Tests;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;

abstract class DataBaseTestCase extends TestCase
{
    use CreatesApplication;
//    use DatabaseMigrations;
    use RefreshDatabase; // This trait is an improvement of DatabaseMigrations

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::statement('PRAGMA foreign_key=on');
    }

//    public function __construct(?string $name = null, array $data = [], string $dataName = '')
//    {
//        parent::__construct($name, $data, $dataName);
//        DB::statement('PRAGMA foreign_key=on');
//    }
}
